name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://marpteam/marp-cli:latest
        with:
          args: docs/index.md -o docs/index.html
        env:
          MARP_USER: root:root
